@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
collections "undoHistory : Deque<Command>" as UndoHistory
participant "c:Command" as PrevCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("undo")
activate AddressBookParser

create UndoCommand
AddressBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> AddressBookParser
deactivate UndoCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> LogicManager : executeUndo()
activate LogicManager

LogicManager -> UndoHistory : peek()
UndoHistory --> LogicManager : c

LogicManager -> PrevCommand : undo(Model)
activate PrevCommand

PrevCommand -> Model : revert changes
activate Model
Model --> PrevCommand
deactivate Model

PrevCommand --> LogicManager : CommandResult
deactivate PrevCommand

LogicManager -> UndoHistory : pop()
UndoHistory --> LogicManager

LogicManager --> LogicManager : result
deactivate LogicManager

[<-- LogicManager
deactivate LogicManager
@enduml
